# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-26 09:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20160920_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Window',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_recorded', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time recorded')),
                ('value', models.CharField(max_length=10)),
            ],
        ),
    ]
