# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-25 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20161010_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='coffee',
            field=models.BooleanField(default=False, verbose_name='Coffee'),
        ),
    ]
