#!/bin/bash
ffmpeg -f alsa -ac 2 -i hw:1 -f v4l2 -framerate 30 -video_size 640x480 \
-i /dev/video0 -vcodec libx264 -preset veryfast -maxrate 1984k -bufsize 3968k \
-vf "format=yuv420p" -g 60 -c:a aac -b:a 128k -ar 44100 \
-f flv rtmp://live.twitch.tv/app/live_135514651_a36ejEHMcpvTXGzCTx7XIQGj4sKwnL
