#!/bin/bash

ffmpeg -f v4l2 -framerate 10 -video_size 320x240 -i /dev/video0 \
	-thread_queue_size 1024 -f alsa -ar 44100 -ac 1 -i hw:1 -c:a aac -b:a 64k \
	-vcodec libx264 -preset ultrafast -r 10 -s 320x240 -crf 23 \
	 -vf "format=yuv420p" -g 30\
	-f flv rtmp://localhost/live/
